### ISSUE TITLE
stdio missing from package.json

### ISSUE THREAD

**Issue by conradj** [vicchi/node-getpocket#6]
Running `node_modules/node-getpocket/authorise --consumerkey 'YOUR-CONSUMER-KEY'` provides the following error:

`Error: Cannot find module 'stdio'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/example/node_modules/node-getpocket/authorise.js:7:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)`

Running `npm install --save stdio` resolves the issue locally.

**Comment by vicchi** [comment]
@conradj - Yikes. Nicely spotted and thanks for reporting. This should now be fixed on `master` from commit `8be2cb2`
